server:
  port: 8080
  servlet:
    context-path: /exp_management/api/v1

spring:
  main:
    allow-circular-references: true
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: jrobert
      password: admin

jwt:
  secret: Um9iZXJ0QDIyMDU=
